package tests

import "strings"

func editRevisions(s *S) {
	c := s.fresh()
	page := c.page("Revision witness")
	revision := func(id int64) int64 { return c.n("SELECT revision FROM entities WHERE id=?", id) }
	s.K("an edit revision starts positive", revision(page) > 0)
	nameBefore := revision(page)
	c.must("INSERT INTO entity_names(entity_id,title,name_key) VALUES (?,'Revision alias','revision alias')", page)
	s.K("owned alias insertion advances revision", revision(page) > nameBefore)
	nameBefore = revision(page)
	c.must("UPDATE entity_names SET title='REVISION ALIAS' WHERE entity_id=? AND name_key='revision alias'", page)
	s.K("equivalent owned spelling edit advances revision", revision(page) > nameBefore)
	nameBefore = revision(page)
	c.must("UPDATE entities SET preferred_name_key='revision alias' WHERE id=?", page)
	s.K("already-owned preferred selection advances revision", revision(page) > nameBefore)
	nameBefore = revision(page)
	c.must("UPDATE entity_names SET title=title WHERE entity_id=?", page)
	c.must("UPDATE entities SET preferred_name_key=preferred_name_key WHERE id=?", page)
	c.must("INSERT INTO entity_names(entity_id,title,name_key) VALUES (?,'REVISION ALIAS','revision alias') ON CONFLICT(name_key) DO NOTHING", page)
	s.K("owned spelling selection and conflict no-ops preserve revision", revision(page) == nameBefore)
	c.must("BEGIN IMMEDIATE")
	c.must("INSERT INTO entity_names(entity_id,title,name_key) VALUES (?,'Rollback alias','rollback alias')", page)
	c.must("UPDATE entity_names SET title='Revision Alias' WHERE name_key='revision alias'")
	c.must("UPDATE entities SET preferred_name_key='rollback alias' WHERE id=?", page)
	c.must("ROLLBACK")
	s.K("owned name changes rollback spelling selection and revision", revision(page) == nameBefore && c.str("SELECT preferred_name_key FROM entities WHERE id=?", page) == "revision alias" && c.str("SELECT title FROM entity_names WHERE name_key='revision alias'") == "REVISION ALIAS" && c.n("SELECT count(*) FROM entity_names WHERE name_key='rollback alias'") == 0)
	_, zeroErr := c.tryIdentity("page", "Zero revision", M{"revision": 0})
	s.K("zero revision refused", zeroErr != nil && strings.Contains(zeroErr.Error(), "entities_revision"))
	c.must("UPDATE entities SET revision=5 WHERE id=?", page)
	s.K("revision decrease refused", strings.HasPrefix(c.tryx("UPDATE entities SET revision=4 WHERE id=?", page), "ERR"))
	before := revision(page)
	c.must("UPDATE entities SET body=body WHERE id=?", page)
	s.K("body no-op preserves revision", revision(page) == before)
	c.must("BEGIN IMMEDIATE")
	c.must("UPDATE entities SET body='rollback' WHERE id=?", page)
	c.must("ROLLBACK")
	s.K("rollback restores revision", revision(page) == before)
	c.must("UPDATE entities SET body='committed' WHERE id=?", page)
	s.K("body changes advance revision", revision(page) > before)
	before = revision(page)
	c.must("UPDATE entities SET deleted_at="+NOW+" WHERE id=?", page)
	s.K("lifecycle changes advance revision", revision(page) > before)
	before = revision(page)
	c.must("UPDATE entities SET updated_at='2020-01-01T00:00:00.000Z' WHERE id=?", page)
	s.K("clock alone does not advance revision", revision(page) == before)
	for _, typ := range []string{"person", "metric", "file"} {
		id := c.identity(typ, "ui", "Detail "+typ, nil, "")
		before = revision(id)
		c.domain(typ, id, nil)
		s.K(typ+" detail insertion advances revision", revision(id) > before)
		if typ == "person" {
			before = revision(id)
			c.must("UPDATE people SET name='changed' WHERE id=?", id)
			s.K("person details advance revision", revision(id) > before)
		}
		if typ == "file" {
			before = revision(id)
			c.must("UPDATE files SET preview=? WHERE id=?", jpegBytes, id)
			s.K("file details advance revision", revision(id) > before)
		}
	}
	place := c.named("place", "")
	before = revision(place)
	c.must("INSERT INTO places(id,lat,lon,radius_m) VALUES(?,1,2,30)", place)
	s.K("place detail insertion advances revision", revision(place) > before)
	before = revision(place)
	c.must("UPDATE places SET lat=3 WHERE id=?", place)
	s.K("place details advance revision", revision(place) > before)
	metric := c.metric("Revision habit", "")
	before = revision(metric)
	c.must("INSERT INTO habit_periods(metric_id,start_day,source) VALUES(?,'2026-01-01','ui')", metric)
	s.K("habit insertion advances revision", revision(metric) > before)
	before = revision(metric)
	c.must("UPDATE habit_periods SET end_day='2026-01-02' WHERE metric_id=?", metric)
	s.K("habit edits advance revision", revision(metric) > before)
	other := c.page("Other endpoint")
	before = revision(page)
	c.must("INSERT INTO links(from_id,to_id,kind,created_at,source) VALUES(?,?,'part-of',"+NOW+",'ui')", page, other)
	s.K("link insertion advances revision", revision(page) > before)
	before = revision(page)
	c.must("UPDATE links SET note='note' WHERE from_id=? AND to_id=?", page, other)
	s.K("link note edit advances revision", revision(page) > before)
	before = revision(page)
	c.must("DELETE FROM links WHERE from_id=? AND to_id=?", page, other)
	s.K("link deletion advances revision", revision(page) > before)
	c.must("UPDATE entities SET revision=9223372036854775807 WHERE id=?", page)
	s.K("revision exhaustion refuses edit", strings.HasPrefix(c.tryx("UPDATE entities SET body='overflow' WHERE id=?", page), "ERR") && c.str("SELECT body FROM entities WHERE id=?", page) == "committed" && revision(page) == 9223372036854775807)
}
