# (label, body, expected titles extracted+valid, in order of first appearance, de-duplicated by key)
# Written BEFORE the reference implementation was first run.
A240 = 'a' * 240; A241 = 'a' * 241; J80 = '日' * 80; J81 = '日' * 81
V = [
 # wikilinks
 ('plain',            'See [[Diet plan]].',                       ['Diet plan']),
 ('alias',            '[[Diet plan|my diet]]',                    ['Diet plan']),
 ('trim',             '[[  Diet plan  ]]',                        ['Diet plan']),
 ('hash-in-title',    '[[C#]] and [[Page#Section]]',              ['C#', 'Page#Section']),
 ('slash',            '[[Health/Diet]]',                          []),
 ('colon',            '[[Re: plan]]',                             []),
 ('empty',            '[[]] [[ ]] [[|alias]]',                    []),
 ('newline inside',   '[[multi\nline]]',                          []),
 ('dup by key',       '[[Café]] [[CAFÉ]] [[Café]] [[cafe]]', ['Café', 'cafe']),
 ('first spelling',   '[[Diet]] [[diet]]',                        ['Diet']),
 ('nested brackets',  '[[nested [[x]] y]]',                       ['x']),
 ('no escape',        r'\[[escaped]]',                            ['escaped']),
 ('inline code',      'text `[[code]]` text',                     []),
 ('fenced code ~',      'a\n\n~~~\n[[fence]]\n~~~\n\nb',           []),
 ('fenced code',      'a\n\n```\n[[fence]]\n#fencetag\n```\n\nb',  []),
 ('indented code',    'a\n\n    [[indented]]\n\nb',               []),
 ('html',             '<span>[[html]]</span> <!-- [[cm]] -->',    ['html']),   # text between tags is text; comments are not
 ('image alt',        '![alt [[img]]](u.png)',                    []),
 ('link label',       '[see [[Diet]]](http://x)',                 ['Diet']),
 ('markdown link',    '[[Diet]](http://y)',                       []),
 ('markup inside',    '[[Health *Diet*]]',                        []),
 ('ref definition',   '[[Ref]]\n\n[Ref]: http://r',               []),
 ('dots',             '[[.hidden]] [[trail.]] [[a.b]]',           ['a.b']),
 ('devices',          '[[CON]] [[nul]] [[Com1]] [[CONSOLE]] [[COM10]] [[LPT0]]', ['CONSOLE', 'COM10', 'LPT0']),
 ('devices with extension', '[[CON.backup]] [[nul.txt]] [[COM\u00b9]] [[LPT\u00b2.x]] [[a.CON]] [[CONSOLE.txt]]', ['a.CON', 'CONSOLE.txt']),
 ('tab inside',       '[[tab\there]]',                            []),
 ('240 bytes',        f'[[{A240}]]',                              [A240]),
 ('241 bytes',        f'[[{A241}]]',                              []),
 ('80 CJK = 240 B',   f'[[{J80}]]',                               [J80]),
 ('81 CJK = 243 B',   f'[[{J81}]]',                               []),
 ('wiki + alias in heading', '# Plan for [[Diet plan|it]]',       ['Diet plan']),
 # tags
 ('tag',              'Feeling good #health today',               ['health']),
 ('tag case',         '#Health and #health and #HEALTH',          ['Health']),
 ('tag unicode',      '#日本語 #zürich #a_b-c',                   ['日本語', 'zürich', 'a_b-c']),
 ('tag punctuation',  '#tag. #tag2, (#paren) "#quoted" #end-',    ['tag', 'tag2', 'paren', 'quoted', 'end']),
 ('tag at line start','line\n#second\n#third',                    ['second', 'third']),
 ('heading is not a tag', '# Heading\n\n## Sub\n\n### Sub sub',   []),
 ('hash without space','#Heading',                                ['Heading']),
 ('C# F# a#b',        'I write C# and F# and a#b',                []),
 ('url fragments',    '[a](http://x/#frag) <http://x/#auto> http://x/#bare', []),
 ('numbers',          'issue #12 and #2024 but #2024-review',     ['2024-review']),
 ('double hash',      '##tag',                                    []),
 ('bare hash',        '# and # alone #',                          []),
 ('tag in code',      '`#code` and #real',                        ['real']),
 ('tag beside wikilink', '[[Project #alpha]] #beta [[#gamma]]',   ['Project #alpha', 'beta', '#gamma']),
 ('device tags',      '#con #nul #console',                       ['console']),
 ('tag slash',        '#work/project',                            ['work']),
 ('tag NFD',          '#cafe\u0301 #zu\u0308rich',               ['café', 'zürich']),
 ('tag Devanagari',   '#हिन्दी and #ひらがな',                      ['हिन्दी', 'ひらがな']),
 ('tag after mark',   'e\u0301#tag',                              []),
 ('wikilink NFD',     '[[Cafe\u0301 notes]]',                     ['Café notes']),
 # stubs
 ('redirect stub',    '#REDIRECT [[New Title]]',                  []),
 ('redirect stub lc', '  #redirect  [[New Title]]\nmore #tag',    []),
 ('redirect not first','see #REDIRECT [[New Title]]',             ['New Title']),
 ('redirect as text','#redirectors are fun',                      ['redirectors']),
]
